# Generated by Django 5.0.3 on 2024-04-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='app.genre'),
        ),
    ]
